#!/bin/bash

rm out/*

genomer view table                 \
  --identifier=PRJNA68653          \
  --reset_locus_numbering          \
  --prefix='I1A_'                  \
  --create_cds='gnl|BartonUAkron|' \
  > out/plasmid.tbl

genomer view fasta                                 \
  --identifier=PRJNA68653                          \
  --organism='Pseudomonas fluorescens'             \
  --strain='R124'                                  \
  --gcode='11'                                     \
  --topology='circular'                            \
  --isolation-source='Orthoquartzite Cave Surface' \
  --collection-date='17-Oct-2007'                  \
  --completeness='Complete'                        \
  > out/plasmid.fsa

cp submission/template.sbt out/plasmid.sbt

tbl2asn -p out -V vb
